// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfh224EOicBpuKSYUsD9d96gr2WDzGlFg',
    appId: '1:200636691636:web:cee1e0de9b7395192e93e1',
    messagingSenderId: '200636691636',
    projectId: 'flash2ride',
    authDomain: 'flash2ride.firebaseapp.com',
    storageBucket: 'flash2ride.firebasestorage.app',
    measurementId: 'G-JFHEJEYW0D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdlDBhluu9VagPdCTlepxiV1DHgJ-rgjg',
    appId: '1:200636691636:android:bbb36ab5022c2bf62e93e1',
    messagingSenderId: '200636691636',
    projectId: 'flash2ride',
    storageBucket: 'flash2ride.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeDRYaQ6I7Ii_NW0PLJwcy9QZNOCiPQRE',
    appId: '1:200636691636:ios:ff9f90f9c66dfa422e93e1',
    messagingSenderId: '200636691636',
    projectId: 'flash2ride',
    storageBucket: 'flash2ride.firebasestorage.app',
    androidClientId: '200636691636-0u0loopt3nng1m9k77bje9n3f92ualkv.apps.googleusercontent.com',
    iosBundleId: 'com.flash2ride.flash2Ride',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeDRYaQ6I7Ii_NW0PLJwcy9QZNOCiPQRE',
    appId: '1:200636691636:ios:ff9f90f9c66dfa422e93e1',
    messagingSenderId: '200636691636',
    projectId: 'flash2ride',
    storageBucket: 'flash2ride.firebasestorage.app',
    androidClientId: '200636691636-0u0loopt3nng1m9k77bje9n3f92ualkv.apps.googleusercontent.com',
    iosBundleId: 'com.flash2ride.flash2Ride',
  );
}
